# GitHub Dependabot configuration for typed-json-db
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    # Group all dependency updates together into a single PR
    groups:
      all-dependencies:
        patterns:
          - "*"
    # Limit to 1 PR since we're grouping everything
    open-pull-requests-limit: 1
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    # Group all GitHub Actions updates together
    groups:
      all-actions:
        patterns:
          - "*"
    # Limit to 1 PR since we're grouping everything
    open-pull-requests-limit: 1
    commit-message:
      prefix: "ci"
      include: "scope"
